[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kujira"
version = "0.1.0"
description = "Live, editable analytics."
authors = [{name = "Abitpal Gyawali", email = "agyawali@utexas.edu"}, {name = "Varun Ragunath"}]
dependencies = []


